# Generated by Django 4.2.1 on 2023-06-06 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debit',
            name='historal_crediticio',
        ),
    ]
