# Generated by Django 4.1.7 on 2023-06-08 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_user', models.IntegerField()),
                ('card_user_to_transfer', models.IntegerField()),
                ('concept', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='card.debit')),
                ('transactions_user', models.ManyToManyField(to='transaccion.transferencia')),
            ],
        ),
    ]
