# Generated by Django 4.2.1 on 2023-06-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0002_alter_profile_direccion_alter_profile_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dni',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
